#ifndef InterruptHandler_h
#define InterruptHandler_h

typedef void (*InterruptHandler_cbkFun)(void);

void InterruptHandler_main(void);
void InterruptHandler_registerRealAccelerometerDataAvailableIntCbk(InterruptHandler_cbkFun const realAccelerometerDataAvailableIntCbk);
void InterruptHandler_registerAccelerometerSimulatorDataAvailableIntCbk(
    InterruptHandler_cbkFun const accelerometerSimulatorDataAvailableIntCbk
);
void InterruptHandler_registerPushButtonPressIntCbk(InterruptHandler_cbkFun const pushButtonPressIntCbk);

#endif // InterruptHandler_h
