= Introduction to Object-Oriented Programming in C for Embedded Systems
:sectnums:
:imagesdir: media

== Object-Oriented Programming (OOP)
Object-oriented programming (OOP) is a programming paradigm that revolves around the concept of objects, which encapsulate data and behavior. In OOP, programs are designed by creating classes, which serve as templates for creating objects. Each object has its own set of properties and methods, which can be used to manipulate or interact with the object.
One of the main advantages of OOP is its ability to organize complex code into smaller, more manageable pieces. This makes it easier to write, test, and maintain code, especially in large-scale projects. Additionally, OOP promotes code reusability, as classes can be reused across multiple projects.

== Advantages of OOP in Embedded Systems
* Code reusability: Reuse existing classes and libraries across projects
* Modularity: Divide complex systems into smaller, manageable objects
* Maintainability: Changes in one object have minimal impact on other objects
* Encapsulation: Protects data and implementation details from external access

== OOP in c?
OOP is a programming paradigm.

The concept of OOP emerged before the development of specific programming languages designed for it. OOP principles and ideas were initially conceived as a way to organize and structure software systems, and they later influenced the creation of programming languages that supported those concepts.

While C is not inherently an object-oriented language, it is possible to implement OOP principles through the use of structs, functions and function pointers. Structs can be used to define objects, while functions and function pointers can be used to define methods that operate on those objects.
One popular approach to implementing OOP in C is the use of a struct-based inheritance model, where child structs inherit properties and methods from parent structs. This allows for code reuse and promotes modularity.

When implementing OOP in C for embedded systems, it is important to follow best practices to ensure code quality and maintainability. This includes proper memory management, avoiding global variables, and adhering to coding standards.

== Encapsulation and Data Hiding
* Encapsulation: Bundling data and functions into a single unit (class)
* Data hiding: Restricting access to internal data of a class


=== Example in C:
[plantuml, target=diag-object-class-uml-representation]
.Object class UML representation
----
class Object {
    + attribute : uint32_t
    + init() : void
    + setAttribute(attribute : uint32_t) : void
    + getAttribute() : uint32_t
}
----

==== Encapsulation
.Object.h
[source,c]
----
typedef struct {
    uint32_t attribute;
} Object;

void Object_init(Object * const self);
void Object_setAttribute(Object * const self, uint32_t const attribute);
uint32_t Object_getAttribute(Object * const self);
----

.Object.c
[source,c]
----
#include "Object.h"

void Object_init(Object * const self) {
    self->attribute = 0;
}

void Object_setAttribute(Object * const self, uint32_t const attribute) {
    self->attribute = attribute;
}
uint32_t Object_getAttribute(Object * const self) {
    return self->attribute;
}
----

.main.c
[source,c]
----
#include "Object.h"

int main() {
    Object obj;
    Object_init(&obj);                      // new Object();
    Object_setAttribute(&obj, 5);           // obj.setAttribute(5);
    uint32_t a = Object_getAttribute(&obj); // obj.getAttribute();
    return 0;
}
----

==== Data hiding
.Object.h
[source,c]
----
typedef struct Object Object;

Object * Object_getInstance(void);
void Object_setAttribute(Object * const self, uint32_t const attribute);
uint32_t Object_getAttribute(Object * const self);
----

.Object.c
[source,c]
----
#include "Object.h"

struct Object {
    uint32_t attribute;
};

static void Object_init(Object * const self) {
    self->attribute = 0;
}

Object * Object_getInstance(void) {
    static Object self;
    static bool isInitialized = false;
    if (isInitialized == false) {
        Object_init(&self);
        isInitialized = true;
    }
    return &self;
}

void Object_setAttribute(Object * const self, uint32_t const attribute) {
    self->attribute = attribute;
}
uint32_t Object_getAttribute(Object * const self) {
    return self->attribute;
}
----

.main.c
[source,c]
----
#include "Object.h"

int main() {
    Object * obj = Object_getInstance();   // Object.getInstance();
    Object_setAttribute(obj, 5);           // obj.setAttribute(5);
    uint32_t a = Object_getAttribute(obj); // obj.getAttribute();
    return 0;
}
----

== Abstraction and Modularity
* Abstraction: Simplifying complex systems by representing essential features
* Modularity: Breaking down a system into independent and reusable components (classes)

=== Example in C:
[plantuml, target=diag-timer-class-uml-representation]
.Timer class UML representation (Timer depends on TimeSource)
----
class Timer {
    + startTimeInMillis : uint32_t
    + delayInMillis : uint32_t
    + init() : Timer
    + start(delayInMillis : uint32_t) : void
    + stop() : void
    + isExpired() : bool
}
interface TimeSource {
    + getCurrentTimeInMillis() : uint32_t
}
Timer .r.> TimeSource
----

.Timer.h
[source,c]
----
typedef struct {
    uint32_t startTimeInMillis;
    uint32_t delayInMillis;
} Timer;

Timer * Timer_init(Timer * const self);
void Timer_start(Timer * const self, uint32_t const delayInMillis);
void Timer_stop(Timer * const self);
bool Timer_isExpired(Timer const * const self);
----

.Timer.c
[source,c]
----
#include "Timer.h"
#include "TimeSource.h"

Timer * Timer_init(Timer * const self) {
    self->startTimeInMillis = 0;
    self->delayInMillis = 0;
    return self;
}

void Timer_start(Timer * const self, uint32_t const delayInMillis) {
    self->startTimeInMillis = TimeSource_getCurrentTimeInMillis();
    self->delayInMillis = delayInMillis;
}

void Timer_stop(Timer * const self) {
    Timer_init(self);
}

bool Timer_isExpired(Timer const * const self) {
    return (
        (self->startTimeInMillis != 0) &&
        ((TimeSource_getCurrentTimeInMillis() - self->startTimeInMillis) >= self->delayInMillis)
    );
}
----

.main.c
[source,c]
----
#include "Timer.h"

int main() {
    Timer * timer = Timer_init(&(Timer){0}); // new Timer();
    for (uint8_t index = 0; index < 5; index++) {
        Timer_start(timer, 1000);                     // timer.start(1000);
        while (Timer_isExpired(timer) == false) { ; } // timer.isExpired()
        printf("%d\n", index + 1);
    }
    return 0;
}
----

== Inheritance and Polymorphism
* Inheritance: Creating new classes (derived classes) based on existing classes (base classes)
* Polymorphism: Ability of objects to take on different forms or behaviors

=== Example in C:
[plantuml, target=diag-shape-and-rectangle-class-uml-representation]
.Shape and Rectangle class UML representation (Rectangle extends Shape)
----
class Shape {
    + x : uint32_t
    + y : uint32_t
    + init(x : uint32_t, y : uint32_t) : Shape
    + {virtual} area() : float
}
class Rectangle {
    + width : uint32_t
    + height : uint32_t
    + init(x : uint32_t, y : uint32_t, width : uint32_t, height : uint32_t) : Rectangle
    + getWidth() : uint32_t
    + setWidth(width : uint32_t) : void
    + getHeight() : uint32_t
    + setHeight(height : uint32_t) : void
}
Shape <|-d- Rectangle
----

.Shape.h
[source,c]
----
typedef struct Shape Shape;
typedef float (*Shape_area_function)(Shape const * const self);
struct Shape {
    uint32_t x;
    uint32_t y;
    Shape_area_function area;
};

Shape * Shape_init(Shape * const self, uint32_t const x, uint32_t const y);
float Shape_area(Shape const * const self);
----

.Shape.c
[source,c]
----
#include <assert.h>

static float Shape_area_notImplemented(Shape const * const self) {
    assert("Shape_area not implemented" && false);
    (void)self;
    return 0;
}

Shape * Shape_init(Shape * const self, uint32_t const x, uint32_t const y) {
    self->x = x;
    self->y = y;
    self->area = Shape_area_notImplemented;
    return self;
}

float Shape_area(Shape const * const self) {
    return self->area(self);
}
----

.Rectangle.h
[source,c]
----
#include "Shape.h"

typedef struct {
    Shape shape;
    uint32_t width;
    uint32_t height;
} Rectangle;

Rectangle * Rectangle_init(
    Rectangle * const self,
    uint32_t const x, uint32_t const y, uint32_t const width, uint32_t const height
);
uint32_t Rectangle_getWidth(Rectangle const * const self);
void Rectangle_setWidth(Rectangle * const self, uint32_t const width);
uint32_t Rectangle_getHeight(Rectangle const * const self);
void Rectangle_setHeight(Rectangle * const self, uint32_t const height);
float Rectangle_area(Rectangle const * const self);
----

[plantuml, target=diag-rectangle-object-in-memory]
.Rectangle object in memory
----
object Rectangle {
    shape.x
    ..
    shape.y
    ..
    shape.area
    --
    width
    ..
    height
}
----

.Rectangle.c
[source,c]
----
#include "Rectangle.h"

Rectangle * Rectangle_init(
    Rectangle * const self,
    uint32_t const x, uint32_t const y, uint32_t const width, uint32_t const height
) {
    Shape_init((Shape *)self, x, y);
    self->width = width;
    self->height = height;
    self->shape.area = (Shape_area_function)Rectangle_area;
    return self;
}

uint32_t Rectangle_getWidth(Rectangle const * const self) {
    return self->width;
}

void Rectangle_setWidth(Rectangle * const self, uint32_t const width) {
    self->width = width;
}

uint32_t Rectangle_getHeight(Rectangle const * const self) {
    return self->height;
}

void Rectangle_setHeight(Rectangle * const self, uint32_t const height) {
    self->height = height;
}

float Rectangle_area(Rectangle const * const self) {
    return self->width * self->height;
}
----

.main.c
[source,c]
----
include "Rectangle.h"

int main() {
    Rectangle * rectangle = Rectangle_init(&(Rectangle){0}, 0, 0, 5, 10); // new Rectangle(0, 0, 5, 10);
    Shape * shape = (Shape *)rectangle;
    float rectangleArea = Rectangle_area(rectangle); // rectangle.area();
    float shapeArea = Shape_area(shape);             // shape.area();
    return 0;
}
----

== Summary
* OOP organizes code around objects and their interactions
* OOP brings advantages like code reusability, modularity, maintainability, encapsulation
* C supports OOP techniques
* Encapsulation, abstraction, inheritance, and polymorphism are key OOP concepts

== Questions?
